"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "@/lib/api";

const sev: Record<string, string> = {
  low: "bg-emerald-500/15 text-emerald-500 border-emerald-500/30",
  medium: "bg-amber-500/15 text-amber-500 border-amber-500/30",
  high: "bg-rose-500/15 text-rose-500 border-rose-500/30",
  critical: "bg-red-500/20 text-red-500 border-red-500/40",
};

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<any[]>([]);
  const [status, setStatus] = useState("");
  const [selected, setSelected] = useState<Set<number>>(new Set());

  const load = () => {
    api.get("/api/alerts", { params: { status: status || undefined } })
      .then((r) => setAlerts(r.data.items));
  };
  useEffect(() => { load(); }, [status]);

  const ack = async (id: number) => { await api.post(`/api/alerts/${id}/acknowledge`); load(); };
  const resolve = async (id: number) => { await api.post(`/api/alerts/${id}/resolve`); load(); };
  const bulkAck = async () => {
    await Promise.all(Array.from(selected).map((id) => api.post(`/api/alerts/${id}/acknowledge`)));
    setSelected(new Set()); load();
  };
  const toggle = (id: number) => {
    const s = new Set(selected);
    s.has(id) ? s.delete(id) : s.add(id);
    setSelected(s);
  };

  return (
    <div>
      <h1 className="text-2xl font-bold">Alert Center</h1>
      <p className="text-muted text-sm mt-1">Manage review signals generated by the model.</p>

      <div className="mt-6 flex items-center gap-3 flex-wrap">
        <select value={status} onChange={(e) => setStatus(e.target.value)}
          className="bg-fg/[0.04] border border-border rounded-lg px-3 py-2 text-sm">
          <option value="">All statuses</option>
          <option value="new">New</option>
          <option value="acknowledged">Acknowledged</option>
          <option value="resolved">Resolved</option>
          <option value="dismissed">Dismissed</option>
        </select>
        {selected.size > 0 && (
          <button onClick={bulkAck} className="px-3 py-2 rounded-lg bg-indigo-500/20 text-sm">
            Acknowledge {selected.size}
          </button>
        )}
      </div>

      <div className="mt-4 space-y-3">
        {alerts.length === 0 && (
          <div className="bg-surface border border-border rounded-2xl p-12 text-center text-muted">
            No alerts matching filters.
          </div>
        )}
        {alerts.map((a) => (
          <div key={a.id} className="bg-surface border border-border rounded-2xl p-4 flex items-start gap-4">
            <input type="checkbox" checked={selected.has(a.id)} onChange={() => toggle(a.id)} className="mt-1" />
            <div className="flex-1">
              <div className="flex items-center gap-2 flex-wrap">
                <span className={`px-2 py-0.5 rounded-full text-xs border ${sev[a.severity] ?? ""}`}>
                  {a.severity.toUpperCase()}
                </span>
                <span className="text-xs text-muted">{a.category}</span>
                <span className="text-xs text-muted ml-auto">{new Date(a.created_at).toLocaleString()}</span>
              </div>
              <div className="text-sm mt-2">{a.reason}</div>
              {a.transaction_id && (
                <Link href={`/transactions/${a.transaction_id}`} className="text-xs text-indigo-500 hover:underline">
                  View transaction →
                </Link>
              )}
            </div>
            <div className="flex flex-col gap-2 items-end">
              <span className="text-xs text-muted uppercase">{a.status}</span>
              {a.status === "new" && (
                <button onClick={() => ack(a.id)} className="text-xs px-2 py-1 rounded border border-border">Acknowledge</button>
              )}
              {a.status !== "resolved" && (
                <button onClick={() => resolve(a.id)} className="text-xs px-2 py-1 rounded border border-border">Resolve</button>
              )}
            </div>
          </div>
        ))}
      </div>
    </div>
  );
}
